### ISSUE TITLE
env score is different from offical calculator when scope set to changed and MS not defined

### ISSUE THREAD

**Issue by waniks** [security-database/cvssv3#1]
https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:A/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:H/MAC:H/MPR:H/MUI:R/MC:L/MI:N
env score of offical calculator is 5.9 and result of this class is 5.7
i think line 584,588 in method constructWeights and line 770,795 in method calculate must  determine the value of S at the same time

**Comment by security-database** [comment]
Correct, we are investigating. Seem to be an error when MS is not set. Thanks a lot!

**Comment by waniks** [comment]
Yeah. Also thanks for your work, it saved me a lot of time.

**Comment by security-database** [comment]
Correction in dev-master as you will see, multiple errors. Some on MS / MPR and some on EnvScore formula (need 2 RoundUp)

**Comment by security-database** [comment]
Fix on 2.0.2
https://github.com/security-database/cvssv3/releases/tag/v2.0.2

**Comment by waniks** [comment]
I've checked it and this fix seems not good.
e.g: CVSS:3.0/AV:A/AC:L/PR:L/UI:N/S:**U**/C:H/I:H/A:H/MAC:H/MPR:H/MUI:R/MC:L/MI:N
If MS is not defined, you should check S while contructing MPR weight.

**Comment by security-database** [comment]
Check in dev-master, not my best code, but seem to work better. Will try to make it cleaner
Let me know, i will commit a new version

**Comment by waniks** [comment]
```php
//Modified
foreach ($this->vector_input_array as $metric => $value) {
    if ($metric == "MPR" && ($value == "L" || $value == "H")) {
        if ((empty($this->vector_input_array["MS"]) || $this->vector_input_array["MS"] == "X") && $this->vector_input_array['S'] == 'C'
            || $this->vector_input_array["MS"] == "C") {
            $this->weight[$metric] = (float)self::$metrics_level_modified[$metric][$value]["Scope"];
        } elseif ((empty($this->vector_input_array["MS"]) || $this->vector_input_array["MS"] == "X") && $this->vector_input_array['S'] == 'U'
            || $this->vector_input_array["MS"] == "U"){
            $this->weight[$metric] = (float)self::$metrics_level_modified[$metric][$value]["Default"];
        }
    } else {
        if (isset(self::$metrics_level_modified[$metric][$value])) {
            if ($value != 'X') {
                $this->weight[$metric] = (float)self::$metrics_level_modified[$metric][$value];
            } else {
                $this->weight[$metric] = (float)$this->weight[substr($metric, 1)];
            }
        }
    }
}
```
I make a simple test for this code.

**Comment by security-database** [comment]
Yep, just used your code, with some isset() and push it in master-dev. Pleas try ;) If it work (it pass UnitTest) i will push a version. Thanks a lot!

**Comment by waniks** [comment]
It works fine. :smile:
